import { useMemo, useEffect, useRef } from 'react';
import { useForm, UseFormReturn } from 'react-hook-form';
import { Quotation, QuotationSchema } from '@/src/domain/schema/quotation.schema';
import { Customer } from '@/src/domain/schema/customer.schema';
import { useConfirm } from '@/src/design-system/Confirm';
import { useDraft } from '@/src/hooks/useDraft';
import { useAuth } from '@/src/modules/iam';
import { checkQuotationLock } from '@/src/domain/policy/lock.policy';
import { checkA5Policy } from '@/src/modules/iam';
import { useErpLookup } from './useErpLookup';
import { QUOTATION_LOAI, normalizeLoai } from '@/src/domain/enums/quotation-loai';
import { EntityZnsStatus } from '@/src/domain/enums/zns-status';
import { aggregateProducts, computeLineItem } from '@/src/domain/pricing/quotation-pricing';
import { formatUserOfficer } from '@/src/shared/utils/userProfile';
import { zodResolver } from '@hookform/resolvers/zod';

interface UseQuotationFormProps {
  quotation: Quotation | null;
  quotations: Quotation[];
  customers: Customer[];
  allContracts: any[];
  allPayments: any[];
  allDeliveries: any[];
}

export function useQuotationForm({
  quotation,
  quotations,
  customers,
  allContracts,
  allPayments,
  allDeliveries
}: UseQuotationFormProps) {
  const { confirm } = useConfirm();
  const { user, userData } = useAuth();
  
  const { draft, saveDraft, clearDraft, lastSavedAt } = useDraft<Quotation>('quotation', quotation?.id || 'new');
  
  const { canEdit, reason: lockReason } = checkA5Policy(user, userData, quotation);
  
  const businessLock = useMemo(() => {
    if (!quotation) return { locked: false, reason: undefined, blockingDocuments: [] };
    const myContracts = allContracts.filter(c => c.quotationId === quotation.id);
    const myPayments = allPayments.filter(p => p.quotationId === quotation.id);
    const myDeliveries = allDeliveries.filter(d => d.quotationId === quotation.id);
    return checkQuotationLock(quotation, myContracts, myPayments, myDeliveries);
  }, [quotation, allContracts, allPayments, allDeliveries]);
  
  const defaultOfficer = formatUserOfficer(userData, user);
  
  const form: UseFormReturn<Quotation> = useForm<Quotation>({
    resolver: zodResolver(QuotationSchema) as any,
    defaultValues: quotation ? { ...quotation, nguoiPhuTrach: quotation.nguoiPhuTrach || defaultOfficer } : draft ? { ...draft, nguoiPhuTrach: draft.nguoiPhuTrach || defaultOfficer } : { 
      tinhTrangBaoGia: 'MỚI',
      ngayBaoGia: new Date().toISOString().split('T')[0],
      hieuLuc: 7,
      trangThaiGuiTinBaoGia: EntityZnsStatus.CHUA_GUI,
      products: [],
      loai: QUOTATION_LOAI.MAY,
      nguoiPhuTrach: defaultOfficer
    } as any
  });

  const { control, register, handleSubmit, watch, setValue, getValues, trigger, reset, formState: { errors, isSubmitting, isDirty } } = form;

  // Session Sequence Vault & Custom Code Shield
  const codeVaultRef = useRef<Record<string, string>>({});
  const lastAutoGeneratedCodeRef = useRef<string>('');
  const isManualCustomCodeRef = useRef<boolean>(false);

  // Auto-Healing: Khử sạch stale zero lock khi nạp dữ liệu từ Firestore hoặc draft
  useEffect(() => {
    if (quotation) {
      const healedProducts = (quotation.products || []).map(p => computeLineItem(p));
      const healedAggs = aggregateProducts(healedProducts);
      reset({
        ...quotation,
        products: healedProducts,
        noiDungGhiChu: quotation.noiDungGhiChu || '',
        hieuLuc: quotation.hieuLuc ?? 7,
        ngayBaoGia: quotation.ngayBaoGia || new Date().toISOString().split('T')[0],
        nguoiPhuTrach: quotation.nguoiPhuTrach || defaultOfficer,
        loai: quotation.loai || QUOTATION_LOAI.MAY,
        subTotal: healedAggs.totalGross,
        vatAmount: healedAggs.totalVat,
        discountAmount: healedAggs.totalDiscount,
        totalAmount: healedAggs.totalAfterTax
      });
    }
  }, [quotation, reset, defaultOfficer]);

  const currentLoai = watch('loai');
  const isCreating = !quotation?.id;
  
  const { lookupErp, isLookingUp, isErpLocked, setIsErpLocked } = useErpLookup(setValue, getValues, confirm, customers, trigger);

  // Dynamic Sequence Generator with Session Vault & Zero Counter Leakage
  useEffect(() => {
    let isCancelled = false;
    if (isCreating && currentLoai) {
      const currentSo = (getValues('soPhieuBaoGia') || '').trim();
      const normLoai = normalizeLoai(currentLoai) || QUOTATION_LOAI.MAY;
      let expectedPrefix = 'BGM-';
      if (normLoai === QUOTATION_LOAI.VAT_TU) expectedPrefix = 'BGVT-';
      else if (normLoai === QUOTATION_LOAI.DICH_VU) expectedPrefix = 'BGDV-';

      // Check if current code is system auto-generated
      const isSystemCode = !currentSo || 
        currentSo === lastAutoGeneratedCodeRef.current || 
        /^(BGM|BGVT|BGDV|BG)-\d{4}-\d+$/i.test(currentSo);

      // If user typed custom code (e.g. ERP-12345), protect it from overwriting
      if (currentSo && !isSystemCode) {
        isManualCustomCodeRef.current = true;
        return;
      }

      if (isManualCustomCodeRef.current && currentSo) {
        return;
      }

      // If current code already starts with expected prefix, cache and keep
      if (currentSo && currentSo.startsWith(expectedPrefix)) {
        codeVaultRef.current[normLoai] = currentSo;
        lastAutoGeneratedCodeRef.current = currentSo;
        return;
      }

      // Check Session Vault for existing code for this classification (0ms latency, zero counter leak)
      if (codeVaultRef.current[normLoai]) {
        const cachedCode = codeVaultRef.current[normLoai];
        lastAutoGeneratedCodeRef.current = cachedCode;
        setValue('soPhieuBaoGia', cachedCode, { shouldValidate: true, shouldDirty: true });
        return;
      }

      // Fetch atomic next code for this classification
      fetch('/api/workflow/next-code/quotation', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ loai: currentLoai })
      })
        .then(res => res.json())
        .then(data => {
          if (!isCancelled && data.success && data.code) {
            codeVaultRef.current[normLoai] = data.code;
            lastAutoGeneratedCodeRef.current = data.code;
            setValue('soPhieuBaoGia', data.code, { shouldValidate: true, shouldDirty: true });
          }
        })
        .catch(() => {
          // Deterministic offline fallback based on max existing sequence in quotations
          const year = new Date().getFullYear();
          let maxSeq = 0;
          (quotations || []).forEach(q => {
            const code = q.soPhieuBaoGia || '';
            if (code.startsWith(expectedPrefix)) {
              const match = code.match(/(\d+)$/);
              if (match && match[1]) {
                const num = parseInt(match[1], 10);
                if (!isNaN(num) && num > maxSeq) maxSeq = num;
              }
            }
          });
          const nextSeq = maxSeq + 1;
          const fallbackCode = `${expectedPrefix}${year}-${String(nextSeq).padStart(4, '0')}`;
          if (!isCancelled) {
            codeVaultRef.current[normLoai] = fallbackCode;
            lastAutoGeneratedCodeRef.current = fallbackCode;
            setValue('soPhieuBaoGia', fallbackCode, { shouldValidate: true, shouldDirty: true });
          }
        });
    }
    return () => { isCancelled = true; };
  }, [currentLoai, isCreating, setValue, getValues, quotations]);

  const products = watch('products') || [];
  const ngayBaoGia = watch('ngayBaoGia');
  const hieuLuc = watch('hieuLuc');
  const ngayHetHan = watch('ngayHetHan');

  // Live expiration date calculation
  useEffect(() => {
    if (ngayBaoGia && hieuLuc != null) {
      const expirationDate = new Date(ngayBaoGia);
      expirationDate.setDate(expirationDate.getDate() + Number(hieuLuc));
      const calculatedString = expirationDate.toISOString().split('T')[0];
      if (ngayHetHan !== calculatedString) {
        setValue('ngayHetHan', calculatedString, { shouldValidate: true, shouldDirty: true });
      }
    }
  }, [ngayBaoGia, hieuLuc, setValue, ngayHetHan]);

  // SILENT Auto-Save Draft (every 8 seconds)
  useEffect(() => {
    if (!isDirty) return;
    const interval = setInterval(() => {
      saveDraft(getValues());
    }, 8000);
    return () => clearInterval(interval);
  }, [isDirty, saveDraft, getValues]);

  // Automatic calculation of slMay (total products count)
  useEffect(() => {
    const total = products.reduce((sum: number, p: any) => sum + (Number(p.quantity) || 0), 0); 
    if (getValues('slMay') !== total) {
      setValue('slMay', total);
    }
  }, [products, setValue, getValues]);

  // ANCHOR: D4 - Pure Financial Calculations (derived from Line Items)
  const aggs = useMemo(() => aggregateProducts(products), [products]);

  useEffect(() => {
    let shouldUpdate = false;
    if (getValues('subTotal') !== aggs.totalGross) { setValue('subTotal', aggs.totalGross); shouldUpdate = true; }
    if (getValues('vatAmount') !== aggs.totalVat) { setValue('vatAmount', aggs.totalVat); shouldUpdate = true; }
    if (getValues('discountAmount') !== aggs.totalDiscount) { setValue('discountAmount', aggs.totalDiscount); shouldUpdate = true; }
    if (getValues('totalAmount') !== aggs.totalAfterTax) { setValue('totalAmount', aggs.totalAfterTax); shouldUpdate = true; }
    if (shouldUpdate) {
        trigger('totalAmount');
    }
  }, [aggs, getValues, setValue, trigger]);

  return {
    form,
    register,
    handleSubmit,
    setValue,
    getValues,
    watch,
    control,
    errors,
    isSubmitting,
    isDirty,
    
    canEdit,
    lockReason,
    businessLock,
    
    lookupErp,
    isLookingUp,
    isErpLocked,
    setIsErpLocked,
    
    lastSavedAt,
    clearDraft,
    saveDraft,
    
    aggs,
    products,
    ngayHetHan
  };
}
